apiVersion: v1
kind: ReplicationController
metadata:
  annotations:
    openshift.io/deployer-pod.name: ionic-test-c-1-deploy
    openshift.io/deployment-config.latest-version: '1'
    openshift.io/deployment-config.name: ionic-test-c
    openshift.io/deployment.phase: Complete
    openshift.io/deployment.replicas: '1'
    openshift.io/deployment.status-reason: image change
    openshift.io/encoded-deployment-config: >
      {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"ionic-test-c","namespace":"ionic-test","selfLink":"/apis/apps.openshift.io/v1/namespaces/ionic-test/deploymentconfigs/ionic-test-c","uid":"7cc1100c-b8a0-11e7-81fe-3aba2f0cbf89","resourceVersion":"96059","generation":3,"creationTimestamp":"2017-10-24T09:48:28Z","labels":{"app":"ionic-test-c"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["ionic-test-c"],"from":{"kind":"ImageStreamTag","namespace":"ionic-test","name":"ionic-test-c:latest"},"lastTriggeredImage":"172.30.1.1:5000/ionic-test/ionic-test-c@sha256:ca4e7e61a0f10912d48d1b1b2905453b2dcd35e0c8e034bd031cf3ed2bcf403d"}},{"type":"ConfigChange"}],"replicas":1,"test":false,"selector":{"deploymentconfig":"ionic-test-c"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"ionic-test-c","deploymentconfig":"ionic-test-c"}},"spec":{"containers":[{"name":"ionic-test-c","image":"172.30.1.1:5000/ionic-test/ionic-test-c@sha256:ca4e7e61a0f10912d48d1b1b2905453b2dcd35e0c8e034bd031cf3ed2bcf403d","ports":[{"containerPort":8080,"protocol":"TCP"}],"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":2,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"image
      change","causes":[{"type":"ImageChange","imageTrigger":{"from":{"kind":"ImageStreamTag","namespace":"ionic-test","name":"ionic-test-c:latest"}}}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2017-10-24T09:48:28Z","lastTransitionTime":"2017-10-24T09:48:28Z","message":"Deployment
      config does not have minimum availability."}]}}
  creationTimestamp: '2017-10-24T09:50:46Z'
  generation: 2
  labels:
    app: ionic-test-c
    openshift.io/deployment-config.name: ionic-test-c
  name: ionic-test-c-1
  namespace: ionic-test
  ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: ionic-test-c
      uid: 7cc1100c-b8a0-11e7-81fe-3aba2f0cbf89
  resourceVersion: '96421'
  selfLink: /api/v1/namespaces/ionic-test/replicationcontrollers/ionic-test-c-1
  uid: cf3a4ab6-b8a0-11e7-81fe-3aba2f0cbf89
spec:
  replicas: 1
  selector:
    deployment: ionic-test-c-1
    deploymentconfig: ionic-test-c
  template:
    metadata:
      annotations:
        openshift.io/deployment-config.latest-version: '1'
        openshift.io/deployment-config.name: ionic-test-c
        openshift.io/deployment.name: ionic-test-c-1
      creationTimestamp: null
      labels:
        app: ionic-test-c
        deployment: ionic-test-c-1
        deploymentconfig: ionic-test-c
    spec:
      containers:
        - image: >-
            172.30.1.1:5000/ionic-test/ionic-test-c@sha256:ca4e7e61a0f10912d48d1b1b2905453b2dcd35e0c8e034bd031cf3ed2bcf403d
          imagePullPolicy: Always
          name: ionic-test-c
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  fullyLabeledReplicas: 1
  observedGeneration: 2
  replicas: 1
