apiVersion: v1
kind: BuildConfig
metadata:
  name: test-pipeline
  namespace: sos-utilities
  selfLink: /oapi/v1/namespaces/sos-utilities/buildconfigs/icare-dev-pipeline
  creationTimestamp: null
  labels:
    app: jenkins-pipeline-development
    name: microservice-pipeline
    template: application-template-development-pipeline
  annotations:
    pipeline.alpha.openshift.io/uses: >-
      [{"name": "icare-dev", "namespace": "development", "kind":
      "DeploymentConfig"}]
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
  runPolicy: Serial
   source:
    git:
      uri: "https://fmahon@gitlab.consulting.redhat.com/sos/ionic-template-test.git"
  strategy: jenkinsPipelineStrategy
  output: {}
  resources: {}
  postCommit: {}
  nodeSelector: null
status:
  lastVersion: 0
