#!/bin/bash

# run tests
function tests {
  printf "\n Starting pre-commit checks..\n"
  npm test

  if [ "$?" != "0" ]; then
    printf "\nTests have failed, please review and fix before commitng again." >&2
    exit 1
  fi
}

# lint source code
function lint {
  printf "\nTests have passed, linting source-code..\n"
  npm run lint

  if [ "$?" != "0" ]; then
    printf "\nLinting task has failed, please review code-style and fix." >&2
    exit 1
  fi
}

# generate docs
function docs {
  printf "\nAlmost there, generating documentation..\n"
  npm run docs ; git add .
}

tests
lint
docs
